name: Build and Publish

on:
  push:
    branches: [main]
    paths:
      - "idrive/build/**"
  schedule:
    - cron: "12 9 * * *"
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Check for new base image
        if: github.event_name != 'push'
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@v1
        with:
          parent-image: ubuntu:22.04
          my-image: snorre0815/idrive-docker:latest

      - name: Get iDrive version
        id: version
        run: echo "IDRIVE_VERSION=$(./version.sh)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        if: github.event_name == 'push' || steps.check.outputs.out-of-date == 'true'
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: idrive/build
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.IDRIVE_VERSION }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
