name: Build and Publish

on:
  push:
    branches: [main]
    paths:
      - "idrive/build/**"
  schedule:
    - cron: "12 9 * * *"
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get iDrive version
        id: version
        run: echo "IDRIVE_VERSION=$(./idrive/version.sh)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find docker creds
        run: find . -name 'config.json'

      - name: Env vars
        run: printenv
